### PR TITLE
[Task] TDB-71

### PR DESCRIPTION
**Pull request by anjakammer**
- [x] Transaction to rollback collection changes if one sprint throws an Exception
- [x] test this rollback / exception throwing
- [x] collection parameter for update_collection only, throw exception if used somewhere else
- [x] sprint collision validation should get removed, validation is made in Frontend

> In my opinion, should not move the backend other sprints if dates do collide.
> This PR validates if sprint dates collide - like one can expect it from an api.
> I would not move other sprints as a backend, they should be moved via patch route, too.

### CODE REVIEW

**Comment by ghost** [comment]
I would not separate this - the user edits one sprint and can choose to have all other sprints affected - that's one transaction that either fails or succeeds completely, so should be one request. If we send multiple single patch requests, what happens when something is wrong with the last, but all others are already applied? 

We could do the calculations in FE and add a route that handles patching of multiple sprints, but BE would still need to validate all data sent - so not sure if we win anything by that?

I think it makes sense to send an error if sprints collide, IF the flag to move affected sprints is not set - though even then, the user might want overlapping sprints (I think we talked about that), in case, e.g. one sprint needs to be a day longer for some reason, but the next one can already start.

**Comment by anjakammer** [comment]
@mvuajua 
We have a POST on courses/id/sprint-collection - so a PATCH on the same route could make sense.

**Comment by ghost** [comment]
👌

**Comment by anjakammer** [comment]
@mvuajua the endpoint is:
`PATCH courses/:course_id/sprint-collection`
Payload:
```
{  
   "collection":[  
      {  
         id 
         start_date 
         end_date
      },
      {  
         id 
         start_date 
         end_date
      }
   ]
}

```

**Review by ghost — APPROVED** [review]

**Pull request merged**
