### PR TITLE
[Task] Add project enrollment FE

### PR DESCRIPTION
**Pull request by ghost**

### CODE REVIEW

**Comment by anjakammer** [comment]
@mvuajua There is a Problem with travis.
Even when tests are failing, travis is always green:
https://travis-ci.org/mvuajua/topics-driven-backlog/builds/334202466#L1014

I fixed the backend test. Please look at the frontend-Tests, they seem very red, too.

**Comment by ghost** [comment]
@anjakammer they've been red forever.. that's what TDB-97 is for ;) not sure why travis is green anyways - do we want to fix that rn or are we good with manually checking for the rest of the week?

**Comment by anjakammer** [comment]
@mvuajua We can check this issue with travis later on - but I want to get it fixed during the coming week. I can take a look on this.

**Review by anjakammer — APPROVED** [review]
fine, no bugs

**Pull request merged**
