### PR TITLE
[Task] Add sprint-overlapping FE interface

### PR DESCRIPTION
**Pull request by ghost**
- [x] show warning when sprints overlap
- [x] display preview of how sprints will be moved
- [x] option to save normally anyways
- [x] option to save and move other sprints

### CODE REVIEW

**Review by anjakammer — CHANGES_REQUESTED** [review]
Nice Ui, thanks.
I found a little bug:
After moving all sprints, the order of the sprints seems weird:
image

**Comment by ghost** [comment]
@anjakammer hmm, weird. can you give me the exact data you entered to create the sprints, and then which one you changed to what? I've just tried out a few combinations and it always sorts by start date for me.

**Comment by anjakammer** [comment]
@mvuajua I tested it again, the wrong order come right after generating multiple Sprints.
Additionally, there is an issue with new created courses (which are nor seeded):

1. add a new course
2. generate the sprints like this:
new_course
3. after submit, the input fields are clear , and no sprints are visible.
new_course_after_submit
4. If I reload the Page, the sprints are there, but not sorted correctly:
new_course_reload
5. There are also tests failing on travis:
https://travis-ci.org/mvuajua/topics-driven-backlog/builds/334205375#L1019

**Comment by ghost** [comment]
@anjakammer try again please?

**Review by anjakammer — APPROVED** [review]
works now!

**Pull request merged**
