### PR TITLE
[Task] Post /get-token #TDB-131

### PR DESCRIPTION
**Pull request by anjakammer**
- [x] post with payload: email => `<any email in db>`, password => `<any string>`
- [x] returns token  (exp: 24h) + user object
- [x] tests all the things
- [x] skip Auth on frontend#index

### CODE REVIEW

**Comment by ghost** [comment]
- index page needs to be exempt from authentication (frontend can currently not load)
- ~~realm should be configured to use base url or at east something less generic than "Application"~~
- please add some seeds for users so we can test this easier without directly accessing the DB to create a user first
- cache-control header should have the correct max age according to ttl of token

**Comment by anjakammer** [comment]
> index page needs to be exempt from authentication (frontend can currently not load)

@mvuajua 
If the index page is requesting endpoints which needs auth, I cannot do anything. Does the login-page need any information from the API?

**Comment by ghost** [comment]
The index page loads the entire frontend, anything regarding login/permissions will be configured from there. So frontend loads, sees user is not logged in, shows login form, sends that data to api to obtain token, etc. 

The only route that has to be exempt from authentication of all sorts is / (basically the frontend controller), everything else is fine

**Comment by anjakammer** [comment]
@mvuajua is the response ok like this? Because of the ttl, instead of caching-header.
```
{
    "auth_token": {
        "token": "eyJhbGciOiJIUzI1NiJ9.eyJ1c2VyX2lkIjoxLCJleHAiOjE1MTY1NzExNTB9.CEKhHYDZQ3qDTqTatIEZxeAjE48Wsl1abG38LOy6I3A",
        "ttl": 1516571150
    },
    "user": {
        "id": 1,
        "email": "user1@example.com"
    }
}
```

**Comment by ghost** [comment]
@anjakammer perfect!

**Review by ghost — APPROVED** [review]

**Pull request merged**
