### PR TITLE
[WIP][Task] PATCH add Story to sprints #TDB-44

### PR DESCRIPTION
**Pull request by anjakammer**

### CODE REVIEW

**Comment by ghost** [comment]
@anjakammer not sure on this, but I think we can only add stories to a sprint if the sprint hasn't started yet? If yes, that should be validated. Def shouldnt be able to add stories to a past sprint. On that note we should also probably make sure that past sprints cant be changed anymore :thinking:

**Comment by anjakammer** [comment]
You are right. Does the sprint automatically starts by start_date ?

**Comment by ghost** [comment]
I think so, yeah. Since I think we said students shouldn't need to start it themselves.

**Comment by ghost** [comment]
@anjakammer with regards to today's meeting this should be done then?

**Review by ghost — APPROVED** [review]

**Pull request merged**
