### PR TITLE
[Story] Improvements to courses navigation + display

### PR DESCRIPTION
**Pull request by ghost**

### CODE REVIEW

**Comment by ghost** [comment]
I'm not sure what we meant with TDB-153 - I think it was adding a more obvious link to the detail page, which I already added when making courses editable and deletable..

**Comment by anjakammer** [comment]
@mvuajua #154 was about making the title clickable. The button "back to course" is not really visible. Making the subtitle clickable is the best way to do it.

**Comment by ghost** [comment]
@anjakammer I would never get the idea to click the subtitle - but I don't think it'll hurt to have it clickable, so might as well do both.

**Review by anjakammer — APPROVED** [review]
Fine now. Prof. Kleinen tried to go to the course by clicking the subtitle. I saw it :D

**Pull request merged**
