### PR TITLE
[Story] Report page + print CSS

### PR DESCRIPTION
**Pull request by ghost**
- [x] extra report page with possibility to select next sprint
- [x] print CSS for that

### CODE REVIEW

**Review by anjakammer — CHANGES_REQUESTED** [review]
I cannot understand the controls for the report view.
Also, I cannot find the "export" button.

**Comment by ghost** [comment]
Which controls are not clear? I can't change things if you're not telling me what you want changed ^^ 

What's the "export button"? The button to the reports page is on the top right of the project page.

**Comment by anjakammer** [comment]
screenshot from 2018-01-26 22-02-18

I think it is not clear what this control really does.
I think it should be a selection of all sprints which should get displayed. Additionally, they should be the possibility to include the backlog, too.

Nevertheless, I cannot see the export button to export the report (aka print).
If there is no export button, just a few would have the idea to use the browser print button by themselves.

**Comment by ghost** [comment]
The entire point of the control was so that people who "forgot" to print their stuff can go back a sprint and get the view for the sprint they wanted to submit the report for. Aka they forgot to submit the planning for sprint 6, they can select sprint 6, and get the view they need.

I don't think we necessarily need an export button - they don't need to use the PDF, they could also copy it out - but I'll add a text explaining both that and the control.

**Comment by ghost** [comment]
@anjakammer check if it's clearer for you now please.

**Comment by anjakammer** [comment]
@mvuajua I added the button which I meant. Please look into my commit. If it is fine, we can remove the text redarding the printing

**Comment by ghost** [comment]
@anjakammer I know which button you meant, but it's imo not necessary, as everyone knows where the print function is, which is also dependent on the browser and device, so no need to clutter up the user interface anymore. If you do want it in I don't care, but please also add the respective styles that hide the button on devices that do not support window.print and remove the text. Also, button should be hidden in print view.

**Comment by ghost** [comment]
@anjakammer actually just hide the text conditionally though, cause depending on the device, the browsers print function will work, but window.print will not, so it should be displayed if window.print is not available.

**Pull request merged**
