### PR TITLE
[Task] Add shorthand field to courses

### PR DESCRIPTION
**Pull request by ghost**

### CODE REVIEW

**Comment by anjakammer** [comment]
@mvuajua In my opinion, the first course is more readable than the second one (image).
What do you think?
image

**Review by anjakammer — APPROVED** [review]
Would be nice to move the longer title under the short title. Also making it gray and tiny - would be nicer for readability.
If you disagree, feel free to merge it as it is.

**Comment by ghost** [comment]
@anjakammer I don't think I really care.. so might as well have it your way ;)

**Comment by anjakammer** [comment]
@mvuajua oh yes please, I would strongly prefer my way. :grin:

**Pull request merged**
