### PR TITLE
#TDB-33 Position field for stories

### PR DESCRIPTION
**Pull request by anjakammer**
- [x] position field and migration
- [x] add method to change order of stories
- [x] add tests for position updates

### CODE REVIEW

**Review by ghost — CHANGES_REQUESTED** [review]
This looks good but we don't really need the backlog entity rn, since we only have one backlog, until we implement groups - and then we'd have the parent entity we need to figure out the scope for the sorting. 

Seeing as it adds added complexity that we don't really need for now, I'd remove everything to do with backlogs and order the stories as they are.

**Comment by anjakammer** [comment]
@mvuajua the gem I use needs a parent for sorting. Since I do not want to implement the sorting twice in different ways, I need to use some entity as the parent.

**Comment by ghost** [comment]
@anjakammer it doesn't. You don't have to define a scope, you can also just define a column which you order by. Once we implement the groups in the future, add them as scope, done.

**Comment by ghost** [comment]
@anjakammer I also just found this: http://guides.rubyonrails.org/routing.html#limits-to-nesting - which also says no more than 1 level of nesting and in the section below proposes how to do things instead and still "the rails way" :)

**Comment by anjakammer** [comment]
@mvuajua 
So, things todo here:
- [x] remove Backlog entity, adjust routes and tests
- [x] sort all Stories by themselves

Things which will come up in the future:
- Route: `Stories/:story_id/Tasks` [...]
- Route: `Groups/:group_id/Users` [...]
- Relation: 1 Group <-> n Stories
- sorting the stories by group

Right?

**Comment by ghost** [comment]
Sounds about right!

**Review by ghost — APPROVED** [review]

**Pull request merged**
