### PR TITLE
[Task] Replace date fields with semester select in FE #TDB-56

### PR DESCRIPTION
**Pull request by ghost**
- [x] Remove date fields
- [x] Add semester select
- [x] Adjust value of option depending on BE format

Semester select will show current semester (default) and next semester. Creating courses for past semesters doesn't make sense, and any further into the future people shall just wait...

Value is currently just a string "WS 17/18" "SS 18" etc. but can be adjusted.

### CODE REVIEW

**Comment by anjakammer** [comment]
@mvuajua please send `01.04.20xx` for Sommer Semester and `01.10.20xx` for Winter Semester as a start_date a.s.o to the backend.
The frontend is then calculating the desired Output from these dates.
Thanks!

**Comment by ghost** [comment]
@anjakammer done (in YYYY-MM-DD format as with start and end date before) - however you'd still need to adjust the API to accept only the start_date, and the end date should probably be taken out completely, as we can derive it from the start date when using semesters.

**Comment by anjakammer** [comment]
As discussed, I suggest to switch to the following field structure to match a semester:
semester_type => ['W','S']
semester_year => YYYY

The Winter semester of 2017/2018 has the semester_year 2017.

**Comment by ghost** [comment]
@anjakammer done!

**Review by anjakammer — CHANGES_REQUESTED** [review]
I am getting this error on console for the backlog-page.
image

**Comment by ghost** [comment]
That's most likely because you have a story that's cancelled in your db, but the source code for cancelled is not there so it can't display the badge..

**Review by anjakammer — APPROVED** [review]
You were right. :)

**Pull request merged**
